---
sudo: required

services:
  - docker

env:
  - IMG_NAME: debian
    IMG_TAG: jessie
    ANSIBLE_VERSION: 1.9.6
  - IMG_NAME: debian
    IMG_TAG: jessie
    ANSIBLE_VERSION: 2.0.1

script:
  - tests/rundocker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
