---
- name: Execute specific for OS tasks
  include: '{{item}}'
  with_first_found:
    - '{{ansible_distribution}}_{{ansible_distribution_major_version}}.yml'
    - '{{ansible_distribution}}.yml'
    - 'default.yml'
  tags: basenode

- name: Update motd
  copy:
    content: "{{basenode_motd}}"
    dest: /etc/motd
  tags: basenode
