FROM ubuntu:12.04

RUN apt-get update \
    && apt-get install -y  --no-install-recommends --no-install-suggests \
        python-pip \
        build-essential \
        python-dev \
        libssl-dev \
        libffi-dev \
    && pip install -U pip==8.1.2 \
    && ln -s /usr/local/bin/pip /usr/bin/ \
    && pip install -U setuptools==18.0.1 \
    && pip install -U wheel \
    && pip install \
        `# common ansible` \
        pycrypto \
        cryptography \
        jinja2 \
        paramiko \
        PyYAML \
    && rm -rf /var/lib/apt/lists/* /root/.cache
