#!/bin/bash

set -e

cd `dirname $0`

pip install ansible==${ANSIBLE_VERSION}

export ANSIBLE_CONFIG=./ansible.cfg

# syntax check
ansible-playbook test.yml --syntax-check

# first run
ansible-playbook test.yml

# run idempotence.
ansible-playbook test.yml \
    | grep -q 'changed=0.*failed=0' \
    && (echo 'Idempotence test: pass' && exit 0) \
    || (echo 'Idempotence test: fail' && exit 1)
